### PR TITLE
Moved twig rendering to _evaluate()

### PR DESCRIPTION
**Pull request by othercorey**
This adds a function wrapper for fetch() as well.

### CODE REVIEW

**Comment by ADmad** [comment]
LGTM. Though it would be great if we could figure out how to auto set content not under specific block to twig block named content so than we could use `{% block content %}{% endblock %}` instead of `{{ fetch('content') }} in layout.

**Comment by othercorey** [comment]
Maybe we could assign a reference to the blocks as a context variable ... but I don't know how we can make it an official twig block.

**Comment by ADmad** [comment]
I skimmed through Twig docs earlier today and couldn't find a way to programmatically set a twig block easily either, so NVM.

**Comment by othercorey** [comment]
There might be a solution later on, for now just going with this. I don't plan to use layouts with twig personally.

**Pull request merged**
