### PR TITLE
Updated code coverage badge

### PR DESCRIPTION
**Pull request by othercorey**
https://github.com/cakephp/twig-view/issues/255

### CODE REVIEW

**Comment by othercorey** [comment]
@ADmad Can we add twig-view to coveralls? I ported the code coverage build from cakephp.

**Comment by othercorey** [comment]
php-coveralls fails with this:

> [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  coverage_clover XML file is not readable: /home/travis/build/cakephp/twig-v    
  iew/build/logs/clover.xml

**Comment by ADmad** [comment]
This command `vendor/bin/phpunit --verbose --coverage-clover=clover.xml` will generate the file under `/home/travis/build/cakephp/twig-v
iew` not `/home/travis/build/cakephp/twig-v
iew/build/log`.

**Comment by othercorey** [comment]
I'm missing the .coveralls.yml config. I kept checking .travis for it.

**Pull request merged**
